name: Hello World 
on: 
  push:
    branches: 
      - main
      - develop
      - "release/**"
  pull_request:
    branches: 
      - main
      - develop      

jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print index.html content
        run: cat index.html
